//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTTT.Ejemplo.Persona.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int id { get; set; }
        public int idPersona { get; set; }
        public string strCalle { get; set; }
        public string strNumero { get; set; }
        public string strColonia { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
