//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTTT.Ejemplo.Persona.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string strClaveUnica { get; set; }
        public string strNombre { get; set; }
        public string strAPaterno { get; set; }
        public string strAMaterno { get; set; }
        public int idCatSexo { get; set; }
        public string datFechaNacimiento { get; set; }
        public string strCorreoElectronico { get; set; }
        public string strCodigoPostal { get; set; }
        public string strRfc { get; set; }
        public Nullable<int> idCatEstadoCivil { get; set; }
    
        public virtual CatEstadoCivil CatEstadoCivil { get; set; }
        public virtual CatSexo CatSexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
